services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=virtual
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=virtual
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=virtual
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=virtual
    depends_on:
      - db
