# Generated by Django 5.2.1 on 2025-05-25 13:11

import config.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('content_plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', config.utils.CustomAutoField(editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255, null=True)),
                ('media', models.FileField(max_length=500, null=True, upload_to='contents/')),
                ('media_preview', models.FileField(max_length=500, null=True, upload_to='contents/')),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('text', 'Text'), ('image', 'Image')], max_length=10, null=True)),
                ('media_aspect_ratio', models.FloatField(null=True)),
                ('thumbnail', models.FileField(max_length=500, null=True, upload_to='contents/')),
                ('banner', models.FileField(max_length=500, null=True, upload_to='banners/')),
                ('type', models.CharField(choices=[('content', 'Content'), ('message', 'Message')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='content_plan.contentplan')),
                ('main_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_contents', to='content.tag')),
                ('tagged_users', models.ManyToManyField(db_index=True, related_name='tagged_contents', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(db_index=True, related_name='contents', to='content.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'content',
                'verbose_name_plural': 'contents',
                'db_table': 'contents',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', config.utils.CustomAutoField(editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=512, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='content.content')),
            ],
            options={
                'verbose_name': 'Content report',
                'verbose_name_plural': 'Content reports',
                'db_table': 'content_reports',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', config.utils.CustomAutoField(editable=False, primary_key=True, serialize=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='content.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'like',
                'verbose_name_plural': 'likes',
                'db_table': 'content_likes',
            },
        ),
        migrations.CreateModel(
            name='SavedContent',
            fields=[
                ('id', config.utils.CustomAutoField(editable=False, primary_key=True, serialize=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='content.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'saved content',
                'verbose_name_plural': 'saved contents',
                'db_table': 'content_saved',
            },
        ),
    ]
