# Generated by Django 5.2.1 on 2025-05-25 13:11

import config.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPlan',
            fields=[
                ('id', config.utils.CustomAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('price', models.PositiveIntegerField(null=True)),
                ('price_type', models.CharField(choices=[('week', 'Week'), ('month', 'Month'), ('free', 'Free')], default='free', max_length=10)),
                ('trial_days', models.PositiveIntegerField(null=True)),
                ('trial_discount_percent', models.PositiveIntegerField(null=True)),
                ('trial_description', models.TextField(null=True)),
                ('banner', models.ImageField(upload_to='banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'content plan',
                'verbose_name_plural': 'content plans',
                'db_table': 'content_plan',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', config.utils.CustomAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='content_plan.contentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'db_table': 'subscriptions',
                'ordering': ('created_at',),
            },
        ),
    ]
