# Generated by Django 5.2.1 on 2025-05-25 13:11

import apps.chat.models
import config.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', config.utils.CustomAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to='chats/images/')),
                ('is_group', models.BooleanField(default=False)),
                ('is_request', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_chat', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL)),
                ('request_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chat',
                'verbose_name_plural': 'chats',
                'db_table': 'chats',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChatSetting',
            fields=[
                ('id', config.utils.CustomAutoField(editable=False, primary_key=True, serialize=False)),
                ('message_first_permission', models.CharField(choices=[('superhero', 'Superhero'), ('nobody', 'Nobody')], default='superhero', max_length=10)),
                ('response_permissions', models.JSONField(default=apps.chat.models.default_permissions)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chat setting',
                'verbose_name_plural': 'chat settings',
                'db_table': 'chat_settings',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', config.utils.CustomAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
                ('media', models.FileField(null=True, upload_to='messages/media/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('voice', 'Voice')], max_length=10, null=True)),
                ('thumbnail', models.FileField(null=True, upload_to='messages/media/')),
                ('media_aspect_ratio', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chat.chat')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'db_table': 'messages',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', config.utils.CustomAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message read',
                'verbose_name_plural': 'message reads',
                'db_table': 'message_reads',
                'ordering': ('created_at',),
            },
        ),
    ]
